name: DEPLOY_MAIN
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -vzrd
        path: ./
        remote_path: ${{ vars.SSH_PATH }}
        remote_host: ${{ vars.SSH_HOST }}
        remote_user: ${{ vars.SSH_USER }}
        remote_key: ${{ secrets.SSH_SECRET_KEY }}
